language: php
php:
  - '7.2'
  - nightly
branches:
  only:
    - master
cache:
  directories:
    - vendor
matrix:
  allow_failures:
     php: nightly
before_install:
  - ./travis-setup.sh
  - mkdir -p test_output
install:
  - composer install --dev --no-interaction
script:
  - composer run test
  - composer run phan
  - composer run sniff
after_success:
  - travis_retry php vendor/bin/php-coveralls