language: php
php:
  - '7.1'
  - '7.2'
branches:
  only:
    - master
cache:
  directories:
    - vendor
before_install:
  - ./travis-setup.sh
  - mkdir -p test_output
install:
  - composer install --dev --no-interaction
script:
  - composer run test
  - composer run phan
  - composer run sniff
after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=test_output/clover_kahlan.xml --json_path=test_output/coveralls-upload.json