#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

try {
    $invocation = new \Kavinsky\CloverMerge\Invocation($argv);
    exit ((int)(!$invocation->execute()));
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
